### ISSUE TITLE
Win 2008 R2 seems to be having issues with ConvertTo-JSON

### ISSUE THREAD

**Issue by jefrazie** [voxpupuli/puppet-windowsfeature#71]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.2.1
- Ruby: 1.8.7
- Distribution: Windows 2008 R2
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)
    if (versioncmp( $::kernelmajversion, '6.1') >= 0 ) {
      windowsfeature { 'NET-Framework-Core':
        ensure             => present,
        installsubfeatures => true,
        before             => File['C:/AutomatosRPC'],
      }

## What are you seeing
If we need to install the .NET framework, the Puppet run fails stating it cannot find Get-WindowsFeature.

## What behaviour did you expect instead
Get-WindowsFeature installs the .NET framework

## Output log
Error: Failed to apply catalog: Execution of 'C:\Windows\system32\WindowsPowersh
ell\v1.0\powershell.exe Get-WindowsFeature | ConvertTo-JSON' returned 1: The ter
m 'Get-WindowsFeature' is not recognized as the name of a cmdlet, functi
on, script file, or operable program. Check the spelling of the name, or if a p
ath was included, verify that the path is correct and try again.
At line:1 char:19
+ Get-WindowsFeature <<<<  | ConvertTo-JSON
    + CategoryInfo          : ObjectNotFound: (Get-WindowsFeature:String) [],
   CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by james-powis** [comment]
@matthewrstone I commented in the PR but I am not seeing 2008R2 as being useable, self.instances is throwing REXML errors:

```logs
PS C:\Program Files\Puppet Labs\Puppet\sys\ruby\bin> puppet resource windowsfeature --debug --verbose --trace
Debug: Runtime environment: puppet_version=4.5.2, ruby_version=2.1.8, run_mode=user, default_encoding=IBM437
Debug: Facter: searching for custom fact "kernel".
Debug: Facter: searching for kernel.rb in C:/ProgramData\PuppetLabs\puppet\cache\lib\facter.
Debug: Facter: searching for kernel.rb in C:/ProgramData\PuppetLabs\puppet\cache\lib\facter.
Debug: Facter: fact "facterversion" has resolved to "3.2.0".
Debug: Facter: initializing WMI
Debug: Facter: searching "C:\ProgramData\PuppetLabs\facter\facts.d" for external facts.
Debug: Facter: no external facts were found.
Debug: Facter: setting fact "env_windows_installdir" based on the value of environment variable "FACTER_env_windows_inst
alldir".
Debug: Facter: fact "env_windows_installdir" has resolved to "C:\Program Files\Puppet Labs\Puppet".
Debug: Facter: resolving kernel facts.
Debug: Facter: fact "kernel" has resolved to "windows".
Debug: Facter: fact "kernelrelease" has resolved to "6.1.7601".
Debug: Facter: fact "kernelmajversion" has resolved to "6.1".
Debug: Facter: fact "kernelversion" has resolved to "6.1.7601".
Debug: Facter: searching for custom fact "kernelmajversion".
Debug: Facter: searching for kernelmajversion.rb in C:/ProgramData\PuppetLabs\puppet\cache\lib\facter.
Debug: Facter: searching for kernelmajversion.rb in C:/ProgramData\PuppetLabs\puppet\cache\lib\facter.
Debug: Executing: 'C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe Import-Module ServerManager; Get-WindowsFea
ture | ConvertTo-XML -As String -Depth 4 -NoTypeInformation'
Error: Could not run: malformed XML: missing tag start
Line: 4808
Position: 199234
Last 80 unconsumed characters:
< /Property>     <Property Name="Depth">3</Property>     <Property Name="DependsO
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:374:in `pull_event'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:184:in `pull'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/parsers/treeparser.rb:22:in `parse'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/document.rb:287:in `build'
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/rexml/document.rb:44:in `initialize'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/provider/windowsfeature/default.rb:32:in `new'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/provider/windowsfeature/default.rb:32:in `instances'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:1168:in `block in instances'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:1161:in `collect'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:1161:in `instances'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/indirector/resource/ral.rb:24:in `search'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/indirector/indirection.rb:269:in `search'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application/resource.rb:221:in `find_or_save_resources'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application/resource.rb:136:in `main'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:352:in `run_command'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:344:in `block in run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:540:in `exit_on_fail'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:344:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/command_line.rb:128:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/command_line.rb:72:in `execute'
C:/Program Files/Puppet Labs/Puppet/puppet/bin/puppet:5:in `<main>'
```

**Comment by james-powis** [comment]
however the issue bing described in this issue  was alleviated by pinning to the HEAD of the repo as it is today...

**Comment by cdenneen** [comment]
@matthewrstone @igalic @petems still seeing this error with latest tagged release

**Comment by rymurph20** [comment]
Seeing similar issues to @cdenneen 

Error: Failed to apply catalog: Missing end tag for 'Property' (got "Object")
Line: 1072
Position: 46435
Last 80 unconsumed characters:

**Comment by josefprado** [comment]
@cdenneen I´m facing the same issue here while trying to install a windows feature like "Telnet".  It seems not work well in Windows 2008 R2.

Did you had any update on this issue elsewere?

Regards,

Josef

**Comment by igalic** [comment]
i think it's time we added a Windows testing environment to our windows modules

**Comment by TraGicCode** [comment]
I'm going to verify this

**Comment by TraGicCode** [comment]
Work's fine on the latest release when running beaker.  Closing this.

![image](https://user-images.githubusercontent.com/6224270/30697117-7b051c60-9ea3-11e7-8e87-71e0efc5d3c0.png)
